import { motion } from 'framer-motion';
import { HeartHandshake, Leaf, MapPinned, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import PageHero from '../../components/PageHero';
import { images } from '../../data/siteData';

export default function AboutPage() {
  return <><PageHero eyebrow="Our story" title="Sri Lanka, shared with care" text="We design journeys that feel personal, grounded and alive to the island around you." image={images.heritage} /><section className="section container about-intro"><motion.div initial={{ opacity: 0, x: -25 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }}><span className="eyebrow">Born from island curiosity</span><h2>Thoughtful travel begins by listening.</h2><p>Serendib Trails is an academic full-stack travel platform created around one simple belief: the best journeys leave room for people, place and surprise. Our itineraries bring heritage, nature, food and unhurried hospitality into one seamless experience.</p><p>Every route can be adapted around your pace, interests and travel style.</p><Link className="button button--primary" to="/contact">Tell us your travel story</Link></motion.div><div className="about-intro__image"><img src={images.tea} alt="Scenic train through the Sri Lankan tea country" /></div></section><section className="section section--tint"><div className="container value-grid">{[[MapPinned, 'Local perspective', 'Routes shaped around regional knowledge and meaningful encounters.'], [HeartHandshake, 'Human by design', 'Planning support that treats your holiday as more than a transaction.'], [Leaf, 'Lighter footprints', 'Slower journeys and locally rooted choices wherever practical.'], [ShieldCheck, 'Clear & trusted', 'Transparent demo prices, secure authentication and verified hotel links.']].map(([Icon, title, text]) => <article key={title}><span><Icon /></span><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="container final-cta"><div><span className="eyebrow eyebrow--light">Make it yours</span><h2>There is no single way to see Sri Lanka.</h2><p>Tell us what moves you and start shaping a journey with room to breathe.</p></div><Link className="button button--gold" to="/contact">Plan my journey</Link></section></>;
}
